---
deployment:
  tasks:
    - export DEPLOYPATH=/home/windowrepair13/public_html/
    - /bin/cp -R /home/windowrepair13/public_html/test.windowrepair.nyc/* $DEPLOYPATH
  excludes:
    - /home/windowrepair13/public_html/test.windowrepair.nyc/.htaccess
    - /home/windowrepair13/public_html/test.windowrepair.nyc/wp-config.php
    - /home/windowrepair13/public_html/test.windowrepair.nyc/.gitignore
